"""campagnes de relance

Revision ID: 1217380b7bd7
Revises: 25ef8bbcf3dc
Create Date: 2026-08-22 09:14:57.559616
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1217380b7bd7'
down_revision: Union[str, None] = '25ef8bbcf3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tontine_id', sa.Uuid(), nullable=True),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('channels', sa.String(length=120), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('total_amount_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['organization_members.id'], name=op.f('fk_reminder_campaigns_created_by_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['tontine_cycles.id'], name=op.f('fk_reminder_campaigns_cycle_id_tontine_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reminder_campaigns_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_reminder_campaigns_tontine_id_tontines'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_campaigns'))
    )
    op.create_index('ix_reminder_campaigns_org_created', 'reminder_campaigns', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reminder_campaigns_organization_id'), 'reminder_campaigns', ['organization_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('tontine_id', sa.Uuid(), nullable=True),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('member_name', sa.String(length=240), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['reminder_campaigns.id'], name=op.f('fk_reminders_campaign_id_reminder_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['tontine_cycles.id'], name=op.f('fk_reminders_cycle_id_tontine_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], name=op.f('fk_reminders_member_id_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reminders_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['organization_members.id'], name=op.f('fk_reminders_sent_by_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_reminders_tontine_id_tontines'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_campaign_id'), 'reminders', ['campaign_id'], unique=False)
    op.create_index('ix_reminders_member_status', 'reminders', ['member_id', 'status'], unique=False)
    op.create_index(op.f('ix_reminders_organization_id'), 'reminders', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_organization_id'), table_name='reminders')
    op.drop_index('ix_reminders_member_status', table_name='reminders')
    op.drop_index(op.f('ix_reminders_campaign_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_reminder_campaigns_organization_id'), table_name='reminder_campaigns')
    op.drop_index('ix_reminder_campaigns_org_created', table_name='reminder_campaigns')
    op.drop_table('reminder_campaigns')
    # ### end Alembic commands ###
