"""cotisations de caisse

Revision ID: 25ef8bbcf3dc
Revises: f1fad06f4a1a
Create Date: 2026-08-22 06:42:33.526831
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25ef8bbcf3dc'
down_revision: Union[str, None] = 'f1fad06f4a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dues_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('custom_period_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['organization_members.id'], name=op.f('fk_dues_plans_created_by_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dues_plans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dues_plans')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_dues_plans_org_name')
    )
    op.create_index(op.f('ix_dues_plans_organization_id'), 'dues_plans', ['organization_id'], unique=False)
    op.create_table('dues_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], name=op.f('fk_dues_entries_member_id_organization_members'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dues_entries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['dues_plans.id'], name=op.f('fk_dues_entries_plan_id_dues_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dues_entries')),
    sa.UniqueConstraint('plan_id', 'member_id', 'sequence_number', name='uq_dues_entries_plan_member_period')
    )
    op.create_index(op.f('ix_dues_entries_member_id'), 'dues_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_dues_entries_organization_id'), 'dues_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dues_entries_plan_id'), 'dues_entries', ['plan_id'], unique=False)
    op.create_index('ix_dues_entries_plan_status', 'dues_entries', ['plan_id', 'status'], unique=False)
    op.create_table('dues_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=24), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('proof_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['dues_entries.id'], name=op.f('fk_dues_payments_entry_id_dues_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dues_payments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['organization_members.id'], name=op.f('fk_dues_payments_recorded_by_organization_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dues_payments'))
    )
    op.create_index(op.f('ix_dues_payments_entry_id'), 'dues_payments', ['entry_id'], unique=False)
    op.create_index('ix_dues_payments_entry_status', 'dues_payments', ['entry_id', 'status'], unique=False)
    op.create_index(op.f('ix_dues_payments_organization_id'), 'dues_payments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dues_payments_organization_id'), table_name='dues_payments')
    op.drop_index('ix_dues_payments_entry_status', table_name='dues_payments')
    op.drop_index(op.f('ix_dues_payments_entry_id'), table_name='dues_payments')
    op.drop_table('dues_payments')
    op.drop_index('ix_dues_entries_plan_status', table_name='dues_entries')
    op.drop_index(op.f('ix_dues_entries_plan_id'), table_name='dues_entries')
    op.drop_index(op.f('ix_dues_entries_organization_id'), table_name='dues_entries')
    op.drop_index(op.f('ix_dues_entries_member_id'), table_name='dues_entries')
    op.drop_table('dues_entries')
    op.drop_index(op.f('ix_dues_plans_organization_id'), table_name='dues_plans')
    op.drop_table('dues_plans')
    # ### end Alembic commands ###
