"""tontine domain: tontines, participants, cycles, contributions, payments, draws, beneficiaries, payouts, audit

Revision ID: e34d99d863bc
Revises: 63a9a0cbd4cb
Create Date: 2026-08-20 22:45:31.212930
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e34d99d863bc'
down_revision: Union[str, None] = '63a9a0cbd4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tontines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('custom_period_days', sa.Integer(), nullable=True),
    sa.Column('attribution_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('require_all_contributions_before_draw', sa.Boolean(), nullable=False),
    sa.Column('allow_draw_override', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['organization_members.id'], name=op.f('fk_tontines_created_by_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tontines_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tontines')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_tontines_org_name')
    )
    op.create_index(op.f('ix_tontines_organization_id'), 'tontines', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tontines_status'), 'tontines', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor_member_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=240), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('tontine_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_member_id'], ['organization_members.id'], name=op.f('fk_audit_logs_actor_member_id_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_audit_logs_tontine_id_tontines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tontine_id'), 'audit_logs', ['tontine_id'], unique=False)
    op.create_table('tontine_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tontine_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('draw_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_tontine_cycles_tontine_id_tontines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tontine_cycles')),
    sa.UniqueConstraint('tontine_id', 'sequence_number', name='uq_tontine_cycles_sequence')
    )
    op.create_index(op.f('ix_tontine_cycles_tontine_id'), 'tontine_cycles', ['tontine_id'], unique=False)
    op.create_index('ix_tontine_cycles_tontine_status', 'tontine_cycles', ['tontine_id', 'status'], unique=False)
    op.create_table('tontine_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tontine_id', sa.Uuid(), nullable=False),
    sa.Column('organization_member_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_draw_eligible', sa.Boolean(), nullable=False),
    sa.Column('has_received_payout', sa.Boolean(), nullable=False),
    sa.Column('draw_position', sa.Integer(), nullable=True),
    sa.Column('received_cycle_id', sa.Uuid(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_member_id'], ['organization_members.id'], name=op.f('fk_tontine_participants_organization_member_id_organization_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_cycle_id'], ['tontine_cycles.id'], name=op.f('fk_tontine_participants_received_cycle_id_tontine_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_tontine_participants_tontine_id_tontines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tontine_participants')),
    sa.UniqueConstraint('tontine_id', 'draw_position', name='uq_tontine_participants_position'),
    sa.UniqueConstraint('tontine_id', 'organization_member_id', name='uq_tontine_participants_tontine_member')
    )
    op.create_index(op.f('ix_tontine_participants_organization_member_id'), 'tontine_participants', ['organization_member_id'], unique=False)
    op.create_index(op.f('ix_tontine_participants_tontine_id'), 'tontine_participants', ['tontine_id'], unique=False)
    op.create_table('contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tontine_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['tontine_cycles.id'], name=op.f('fk_contributions_cycle_id_tontine_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contributions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['tontine_participants.id'], name=op.f('fk_contributions_participant_id_tontine_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_contributions_tontine_id_tontines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributions')),
    sa.UniqueConstraint('cycle_id', 'participant_id', name='uq_contributions_cycle_participant')
    )
    op.create_index(op.f('ix_contributions_cycle_id'), 'contributions', ['cycle_id'], unique=False)
    op.create_index('ix_contributions_cycle_status', 'contributions', ['cycle_id', 'status'], unique=False)
    op.create_index(op.f('ix_contributions_organization_id'), 'contributions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contributions_participant_id'), 'contributions', ['participant_id'], unique=False)
    op.create_index(op.f('ix_contributions_tontine_id'), 'contributions', ['tontine_id'], unique=False)
    op.create_table('draw_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tontine_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('draw_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period_label', sa.String(length=60), nullable=False),
    sa.Column('winner_participant_id', sa.Uuid(), nullable=True),
    sa.Column('drawn_by', sa.Uuid(), nullable=True),
    sa.Column('override_used', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('proof_reference', sa.String(length=40), nullable=False),
    sa.Column('random_source', sa.String(length=40), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['tontine_cycles.id'], name=op.f('fk_draw_sessions_cycle_id_tontine_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drawn_by'], ['organization_members.id'], name=op.f('fk_draw_sessions_drawn_by_organization_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_draw_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_draw_sessions_tontine_id_tontines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_participant_id'], ['tontine_participants.id'], name=op.f('fk_draw_sessions_winner_participant_id_tontine_participants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draw_sessions'))
    )
    op.create_index(op.f('ix_draw_sessions_cycle_id'), 'draw_sessions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_draw_sessions_organization_id'), 'draw_sessions', ['organization_id'], unique=False)
    op.create_index('ix_draw_sessions_tontine_created', 'draw_sessions', ['tontine_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_draw_sessions_tontine_id'), 'draw_sessions', ['tontine_id'], unique=False)
    op.create_index('uq_draw_sessions_completed_cycle', 'draw_sessions', ['cycle_id'], unique=True, postgresql_where="status = 'completed'", sqlite_where="status = 'completed'")
    op.create_table('beneficiaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tontine_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('draw_session_id', sa.Uuid(), nullable=True),
    sa.Column('expected_payout_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('designated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['tontine_cycles.id'], name=op.f('fk_beneficiaries_cycle_id_tontine_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draw_session_id'], ['draw_sessions.id'], name=op.f('fk_beneficiaries_draw_session_id_draw_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_beneficiaries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['tontine_participants.id'], name=op.f('fk_beneficiaries_participant_id_tontine_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tontine_id'], ['tontines.id'], name=op.f('fk_beneficiaries_tontine_id_tontines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beneficiaries'))
    )
    op.create_index(op.f('ix_beneficiaries_cycle_id'), 'beneficiaries', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_organization_id'), 'beneficiaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_tontine_id'), 'beneficiaries', ['tontine_id'], unique=False)
    op.create_index('uq_beneficiaries_active_cycle', 'beneficiaries', ['cycle_id'], unique=True, postgresql_where="status <> 'cancelled'", sqlite_where="status <> 'cancelled'")
    op.create_table('draw_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draw_session_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('was_eligible', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draw_session_id'], ['draw_sessions.id'], name=op.f('fk_draw_participants_draw_session_id_draw_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['tontine_participants.id'], name=op.f('fk_draw_participants_participant_id_tontine_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draw_participants')),
    sa.UniqueConstraint('draw_session_id', 'participant_id', name='uq_draw_participants_unique')
    )
    op.create_index(op.f('ix_draw_participants_draw_session_id'), 'draw_participants', ['draw_session_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=24), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('proof_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_payments_contribution_id_contributions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['organization_members.id'], name=op.f('fk_payments_recorded_by_organization_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_contribution_id'), 'payments', ['contribution_id'], unique=False)
    op.create_index('ix_payments_contribution_status', 'payments', ['contribution_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=24), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('proof_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_by', sa.Uuid(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], name=op.f('fk_payouts_beneficiary_id_beneficiaries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payouts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['organization_members.id'], name=op.f('fk_payouts_paid_by_organization_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index(op.f('ix_payouts_beneficiary_id'), 'payouts', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_payouts_organization_id'), 'payouts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_organization_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_beneficiary_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index('ix_payments_contribution_status', table_name='payments')
    op.drop_index(op.f('ix_payments_contribution_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_draw_participants_draw_session_id'), table_name='draw_participants')
    op.drop_table('draw_participants')
    op.drop_index('uq_beneficiaries_active_cycle', table_name='beneficiaries', postgresql_where="status <> 'cancelled'", sqlite_where="status <> 'cancelled'")
    op.drop_index(op.f('ix_beneficiaries_tontine_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_organization_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_cycle_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index('uq_draw_sessions_completed_cycle', table_name='draw_sessions', postgresql_where="status = 'completed'", sqlite_where="status = 'completed'")
    op.drop_index(op.f('ix_draw_sessions_tontine_id'), table_name='draw_sessions')
    op.drop_index('ix_draw_sessions_tontine_created', table_name='draw_sessions')
    op.drop_index(op.f('ix_draw_sessions_organization_id'), table_name='draw_sessions')
    op.drop_index(op.f('ix_draw_sessions_cycle_id'), table_name='draw_sessions')
    op.drop_table('draw_sessions')
    op.drop_index(op.f('ix_contributions_tontine_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_participant_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_organization_id'), table_name='contributions')
    op.drop_index('ix_contributions_cycle_status', table_name='contributions')
    op.drop_index(op.f('ix_contributions_cycle_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_tontine_participants_tontine_id'), table_name='tontine_participants')
    op.drop_index(op.f('ix_tontine_participants_organization_member_id'), table_name='tontine_participants')
    op.drop_table('tontine_participants')
    op.drop_index('ix_tontine_cycles_tontine_status', table_name='tontine_cycles')
    op.drop_index(op.f('ix_tontine_cycles_tontine_id'), table_name='tontine_cycles')
    op.drop_table('tontine_cycles')
    op.drop_index(op.f('ix_audit_logs_tontine_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tontines_status'), table_name='tontines')
    op.drop_index(op.f('ix_tontines_organization_id'), table_name='tontines')
    op.drop_table('tontines')
    # ### end Alembic commands ###
